name: burgernook
description: A new Flutter application.
version: 5.0.2+18

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^2.0.15
  share: any
  http: ^0.13.4
  # connectivity: any
  location: ^4.4.0
  #  geocoder: ^0.2.1
  carousel_slider: ^4.1.1
#  provider: ^6.0.3
#  image_picker: ^0.8.5+3
#  path_provider: ^2.0.11
#  fluttertoast: ^8.0.9
  google_maps_flutter: ^2.1.8
  firebase_database: ^9.0.19
  pin_code_text_field: ^1.8.0
  geocoding: ^2.0.4
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.5
  internet_connection_checker: ^0.0.1+4
  equatable: ^2.0.3
  dartz: ^0.10.1
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  country_pickers: ^2.0.0
  cloud_firestore: ^3.3.0
  firebase_messaging: ^12.0.0
  cached_network_image: ^3.2.1
  animated_background: ^2.0.0
#  device_info:
#  markdown:
#  photo_view: any
  url_launcher: any
  flutter_localizations:
    sdk: flutter
  dots_indicator: ^2.1.0
  lottie: ^1.3.0
  shimmer: ^2.0.0
  pin_code_fields: ^7.3.0
  geolocator: ^8.0.1
  flutter_local_notifications: ^9.7.0
  awesome_notifications: ^0.7.0-beta.5
  auto_size_text: ^3.0.0
#  google_fonts: ^2.2.0
#  flutter_bloc: ^8.1.1
#  flutter_app_restart: ^1.0.0
#  flutter_phoenix: "^1.0.0"
  package_info_plus: ^1.4.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.3
  

flutter_icons:
  ios: true
  image_path: "assets/logo2.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - lang/
  fonts:
    - family: NimbusSansT_BlackCondensed
      fonts:
        - asset: assets/font/NimbusSansT-BlackCondensed.otf
    - family: GE_Dinar_One_Light
      fonts:
        - asset: assets/font/GE_Dinar_One_Light.otf
    - family: GE_Dinar_One_Medium
      fonts:
        - asset: assets/font/GE-Dinar-One-Medium.otf
    - family: arlrdbd
      fonts:
        - asset: assets/font/arlrdbd.ttf